<a href="https://colab.research.google.com/github/LazyEpul/Book_Stall/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
w1 , w2, w3 = 0.3, 0.2 ,0.5

In [2]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [5]:
kanto_yeild_apples = w1*kanto_temp + w2*kanto_rainfall + w3*kanto_humidity
kanto_yeild_apples

56.8

In [7]:
print(f'The expected yeild of apples in Kanto region is {kanto_yeild_apples} tons per hectare.')

The expected yeild of apples in Kanto region is 56.8 tons per hectare.


In [8]:
kanto = [73,67,43]
jahto = [91,88,64]
hoenn = [87,134,58]
sinnoh = [102,43,37]
unova = [69,96,70]


In [9]:
weight = [w1,w2,w3]

In [11]:
def crop_yeild(region,weight):
  res = 0
  for x,y in zip(region,weight):
    res+=x*y
  return res

In [13]:
crop_yeild(kanto,weight)

56.8

In [15]:
crop_yeild(jahto,weight)

76.9

In [16]:
crop_yeild(hoenn,weight)

81.9

In [18]:
 !pip install numpy

In [19]:
import numpy as np

In [20]:
kanto = np.array([73,67,43])

In [21]:
kanto

array([73, 67, 43])

In [23]:
weight = np.array([w1,w2,w3])

In [24]:
weight

array([0.3, 0.2, 0.5])

In [25]:
type(kanto)

numpy.ndarray

In [26]:
type(weight)

numpy.ndarray

In [27]:
weight[0]

0.3

In [28]:
kanto[0]

73

In [29]:
a=np.dot(kanto,weight)

In [30]:
a

56.8

In [33]:
climate_data = np.array([[73,67,43],
                        [91,88,64],
                        [87,134,58],
                        [102,43,37],
                        [69,96,70]])

In [34]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
climate_data.shape

(5, 3)

In [36]:
weight

array([0.3, 0.2, 0.5])

In [37]:
weight.shape

(3,)

In [38]:
weight.dtype

dtype('float64')

In [40]:
climate_data.dtype

dtype('int64')

In [41]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [42]:
weight

array([0.3, 0.2, 0.5])

In [44]:
np.matmul(climate_data, weight)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [47]:
climate_data @ weight

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [48]:
import urllib.request

In [52]:
urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x7fb57d421050>)

In [53]:
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [54]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [55]:
weight

array([0.3, 0.2, 0.5])

In [56]:
weight = np.array([0.3, 0.2, 0.5])

In [57]:
weight

array([0.3, 0.2, 0.5])

In [58]:
yeild = climate_data @ weight

In [59]:
yeild

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [60]:
yeild.shape

(10000,)

In [61]:
climate_results = np.concatenate((climate_data,yeild.reshape(10000,1)),axis = 1)

In [62]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [64]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [65]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
np.ones([2,2,3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [67]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.random.rand(3,4)

array([[0.06375917, 0.0911556 , 0.66602919, 0.83512051],
       [0.74967413, 0.26883427, 0.89625008, 0.80129354],
       [0.34872725, 0.02286192, 0.99875674, 0.4763617 ]])

In [70]:
np.random.randn(3,4)

array([[-0.65663974,  0.97247965,  0.36361628,  0.65190774],
       [-1.17715529, -1.43535   ,  1.55674134, -0.31073737],
       [ 1.19001422,  0.10407492,  0.78647083, -1.25542273]])